#!/usr/bin/env sh

source ~/.bash_profile # https://answers.atlassian.com/questions/140339/sourcetree-hook-failing-because-paths-don-t-seem-to-be-set-correctly

git stash -q --keep-index
npm run lint
RESULT=$?
git stash pop -q

[ $RESULT -ne 0 ] && exit 1
exit 0
